services:
  postgres:
    image: postgres:18-alpine
    container_name: graphql-adjt
    environment:
      POSTGRES_DB: gql-fiap
      POSTGRES_USER: graphql
      POSTGRES_PASSWORD: graphql
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/data
    networks:
      - graphql-adjt

volumes:
  pgdata:

networks:
  graphql-adjt: